steps:
# Build docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args: ['build', '-t','gcr.io/$PROJECT_ID/website:$SHORT_SHA', '.']
# Push docker image to cloud storage
- name: 'gcr.io/cloud-builders/docker'
  id: 'push'
  args: ['push', 'gcr.io/$PROJECT_ID/website:$SHORT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy'
  args:
  - 'run'
  - 'deploy'
  - 'website'
  - '--image'
  - 'gcr.io/$PROJECT_ID/website:$SHORT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--service-account'
  - 'website-cloudbuild@$PROJECT_ID.iam.gserviceaccount.com'
images:
  - gcr.io/$PROJECT_ID/website
